# Generated by Django 3.2.5 on 2022-05-03 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20220503_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
